### ISSUE TITLE
Please add to the documentation

### ISSUE THREAD

**Issue by ghost** [kodi1/esp_wd#3]
I have numerous devices built with ESP Home and this does not work.  The host address with or without the password does not work as there is no 'sysinfo' path.  The webserver is enabled for all of my devices.  I have tried both methods as shown, but there is little other documentation.

It would be nice if you could add more than just a couple of examples.  Some explanation and perhaps specific devices or configurations that this is intended for

**Comment by kodi1** [comment]
It's not for ESP Home.
