### ISSUE TITLE
Warning for deprecated entity since HA 110.x

### ISSUE THREAD

**Issue by papperone** [kodi1/esp_wd#4]
Hello, I've a warning on this component since I upgraded to HA 110.x, it seems esp_wd uses deprecated code and may be discontinued to work in the next version; is there any plan to update this handy custom? the error in the log is this one:

> Dettagli registro (WARNING)
> Logger: homeassistant.components.binary_sensor
> Source: components/binary_sensor/__init__.py:174
> Integration: Sensore binario (documentation, issues)
> First occurred: 18:41:39 (1 occurrences)
> Last logged: 18:41:39
> 
> BinarySensorDevice is deprecated, modify **EspSensor** to extend BinarySensorEntity
> 

thanks!

**Comment by kodi1** [comment]
#5
